### ISSUE TITLE
How to extract features of 4096-d(or features from some other layers) with this model?

### ISSUE THREAD

**Issue by hiarsal** [GKalliatakis/Keras-VGG16-places365#12]
Please make sure that the boxes below are checked before you submit your issue. 

Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
    ```
   pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps
    ```

- [ ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
    ```
    pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
    ```

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by GKalliatakis** [comment]
Keras-VGG16-places365 can be used to extract features from an arbitrary intermediate layer just like any other Keras model. 

For more information read the official documentation [HERE](https://keras.io/applications/#extract-features-from-an-arbitrary-intermediate-layer-with-vgg19)
