### ISSUE TITLE
places_utils.py and function preprocess_input

### ISSUE THREAD

**Issue by icarocd** [GKalliatakis/Keras-VGG16-places365#13]
The example given in README uses Image, and it does not call function preprocess_input.
The main Keras documentation, however, uses image.load_img, where image is imported from keras.preprocessing, and always calls preprocess_input which is imported according to the proper cnn architecture.
I have seen the function preprocess_input defined in places_utils.py, but there is no explicit mention about its use. Is it necessary? Should we import it and use it, as the Keras documentation does?

**Comment by GKalliatakis** [comment]
`places_utils.py` goes along the lines of the previous Keras versions (before imagenet_utils code was delegated to `keras_applications` submodule) and is meant to contain utilities for Places data preprocessing.  

So the answer is yes it is necessary just like the original Keras docs suggest.
