### ISSUE TITLE
How to have similar predictions as Places365 Demo

### ISSUE THREAD

**Issue by northtree** [GKalliatakis/Keras-VGG16-places365#15]
Please make sure that the boxes below are checked before you submit your issue. 

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
    ```
   pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps
    ```

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
    ```
    pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
    ```

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

---

From the official demo website: http://places2.csail.mit.edu/demo.html
It will return below results from test image: http://places2.csail.mit.edu/imgs/demo/6.jpg

How could we have the confidence from scene categories, such as ` food_court (0.690)`

> Predictions:
> Type of environment: indoor
> Scene categories: food_court (0.690), cafeteria (0.163)
> Scene attributes: no horizon, enclosed area, man-made, socializing, indoor lighting, cloth, congregating, eating, working

The current `vgg16_places_365` just return categories without confidence (also return different ranking).

> PREDICTED SCENE CATEGORIES:
> cafeteria
> food_court
> restaurant_patio
> banquet_hall
> restaurant

**Comment by northtree** [comment]
@GKalliatakis It seems that the official demo used [ResNet](https://github.com/CSAILVision/places365/blob/master/run_placesCNN_unified.py) instead of `VGG16`

**Comment by albertobeto** [comment]
Different network architecture and training will lead to different prediction score. 
But you can print the confidence with something like:

      predictions_to_return = 5
      preds = model.predict(image)[0]
      top_preds = np.argsort(preds)[::-1][0:predictions_to_return]
      top_preds_score = np.sort(preds)[::-1][0:predictions_to_return]

      for i in range(0, 5):
          print("{:.2f}".format(top_preds_score[i]*100)+'% ' +
                classes[top_preds[i]])
