### ISSUE TITLE
Fine Tuning the model

### ISSUE THREAD

**Issue by ZoulfikarShmayssani** [GKalliatakis/Keras-VGG16-places365#17]
Hello.

How do I fine tune the model in order to add more categories. For example I want to add a category called "hypermarkets".

Thank you in advance.

**Comment by GKalliatakis** [comment]
Hi, 

VGG16-places365 models can be used like every other pretrained Keras model (VGG16, ResNet etc.)
In order to add your own categories you need to follow [the typical transfer-learning workflow](https://keras.io/guides/transfer_learning/#the-typical-transferlearning-workflow).

Hope it helps
