### ISSUE TITLE
Changing batch input shape

### ISSUE THREAD

**Issue by fmaglia** [GKalliatakis/Keras-VGG16-places365#2]
How can I change the batch_input_shape avoiding errors?

Here my code:
`filter_rows = filter_cols = 562
# load json and create model
json_file = open('VGG16_Places365.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
base_model = model_from_json(loaded_model_json)

# load weights into new model
base_model.load_weights("VGG16_Places365_weights.h5")
base_model.batch_input_shape = (1,filter_rows,filter_cols,3)
print("Loaded model from disk")
model = Model(inputs=base_model.input, outputs=base_model.get_layer(str(layer)).output)`

In this way, I obtained this error message:
ValueError: Error when checking : expected data to have shape (1, 224, 224, 3) but got array with shape (1, 562, 562, 3)

**Comment by GKalliatakis** [comment]
Code has now been updated and is fully keras-applications-compatible, which means the models can be utilised like any default keras models (taken from keras.applications).

Please try again with the updated code and comment below.

**Comment by fmaglia** [comment]
Thanks!
I tried the 2 scripts and now I have another problem (both whit VGG16_Places365 and with VGG16_Hubryd_1365):
```
File "Dottorato/vgg16_hybrid_places_1365.py", line 101, in VGG16_Hubrid_1365
    include_top=False)
TypeError: _obtain_input_shape() got an unexpected keyword argument 'include_top'.
```

Finally is there a possibility to change the input shape of a network for every image?
Or can I release the model from the GPU memory for at the next iteration regenerating the same network model with a different input shape?

**Comment by GKalliatakis** [comment]
Check that you are up-to-date with the master branch of Keras. You can update with:
```
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
```

Regarding input shape please refer to the official documentation : 

> input_shape: optional shape tuple, only to be specified if `include_top ` is `False `(otherwise the input shape has to be `(224, 224, 3)` (with `'channels_last'` data format) or  `(3, 224, 224)` (with `'channels_first' `data format). It should have exactly 3 inputs channels, and width and height should be no smaller than 48. E.g.` (200, 200, 3)` would be one valid value.

**Comment by fmaglia** [comment]
>>> import keras
Using TensorFlow backend.
>>> print(keras.__version__)
2.1.1

I'm using the latest version!

**Comment by GKalliatakis** [comment]
Have a look at the following:
- https://yohanes.gultom.me/keras-vgg16-with-different-input-shape/
- https://stackoverflow.com/questions/42187425/how-to-change-input-shape-in-sequential-model-in-keras

**Comment by GKalliatakis** [comment]
Also for 

> TypeError: _obtain_input_shape() got an unexpected keyword argument 'include_top'.

Try changing "include_top" to "require_flatten" (answer taken from https://github.com/rcmalli/keras-squeezenet/issues/13).

**Comment by fmaglia** [comment]
Thanks.
Now it works!
