### ISSUE TITLE
How to train a model using my own dataset?

### ISSUE THREAD

**Issue by xeoi** [GKalliatakis/Keras-VGG16-places365#6]
Please make sure that the boxes below are checked before you submit your issue. 

Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
    ```
   pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps
    ```

- [ ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
    ```
    pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
    ```

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by GKalliatakis** [comment]
You can have a look at the official Keras documentation (look for [_Fine-tune InceptionV3 on a new set of classes_](https://keras.io/applications/). 
Another example can be found at [Building powerful image classification models using very little data](https://blog.keras.io/building-powerful-image-classification-models-using-very-little-data.html).

In general **VGG16-places365 & VGG16-hybrid1365 models can be used for prediction, feature extraction, and fine-tuning just like the genuine canned keras.applications binaries.** 

Have a look at the [examples section](https://github.com/GKalliatakis/Keras-VGG16-places365#examples) in this repo.
